language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
#  - hhvm

services:
  - mysql

env:
  - DB=mysql DB_USER=propel1_test

before_script:
  # MySQL
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS propel1_test_bookstore; DROP DATABASE IF EXISTS propel1_test_bookstore_namespaced; DROP SCHEMA IF EXISTS propel1_test_schema_bookstore; DROP SCHEMA IF EXISTS propel1_test_schema_second_hand_books; DROP SCHEMA IF EXISTS propel1_test_schema_contest; DROP DATABASE IF EXISTS propel1_test_reverse_bookstore; SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE propel1_test_bookstore;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE propel1_test_bookstore_namespaced;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE SCHEMA propel1_test_schema_bookstore;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE SCHEMA propel1_test_schema_second_hand_books;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE SCHEMA propel1_test_schema_contest;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE propel1_test_reverse_bookstore;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE USER \"propel1_test\"@\"localhost\";'; fi" 
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'GRANT ALL ON \`propel1\\_test\\_%\`.* TO \"propel1_test\"@\"localhost\";'; fi"

  # Composer
  - composer self-update
  - composer install --prefer-source

  - ./test/reset_tests.sh

script: phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
